### PR TITLE
Add responder to ping track EiCs

### PR DESCRIPTION
**Pull request by xuanxu**
Deploy after the track teams are created

### CODE REVIEW

**Review by xuanxu — COMMENTED** [review]
Current list of teams to be created:
- aass-eics
- bcm-eics
- pe-eics
- sbcs-eics
- dsais-eics
- ese-eics
- csism-eics
- misc-eics

**Review by xuanxu — COMMENTED** [review]
Teams now exist

**Comment by arfon** [comment]
It works! https://github.com/openjournals/joss-reviews/issues/4857#issuecomment-1279725479

**Comment by xuanxu** [comment]
Yay! 🎉

**Pull request merged**
