### PR TITLE
Allow reminder to sender

### PR DESCRIPTION
**Pull request by xuanxu**
This PR allows to create reminders with `remind me in 15 days`

### CODE REVIEW

**Comment by danielskatz** [comment]
thanks!

**Comment by danielskatz** [comment]
maybe I jumped the gun?  (https://github.com/openjournals/joss-reviews/issues/3680#issuecomment-1286858473)

**Comment by xuanxu** [comment]
😄  yeah, the deploy is in progress yet

**Comment by xuanxu** [comment]
Deployed!

**Pull request merged**
